### ISSUE TITLE
Redis in queue

### ISSUE THREAD

**Issue by jos3duardo** [stitchng/adonis-queue#10]
Do It is necessary to use REDIS for the jobs to work?

**Comment by stitchng** [comment]
Yes it does @jos3duardo . This package depends on [bee-queue](https://github.com/bee-queue/bee-queue) which utilizes REDIS by default. We are working on incorporating other drivers like _rabbitmq_. If you have suggestions: please let us know.

**Comment by stitchng** [comment]
Closing out now.... Since no further activity here
