### ISSUE TITLE
Error: Cannot call Queue#process twice

### ISSUE THREAD

**Issue by MarkDylan49** [stitchng/adonis-queue#4]
I have this error while calling the Queue from the controller `Error: Cannot call Queue#process twice` 
It works when I call the Queue once every after the server has been restarted, but it shows that error every after I call it the apie with that queue in the second time,
this is my code in controller where I called the queue

`await Queue.select('low').andDispatch(new EmailVoucher(voucher_id, emailContents))`

**Comment by stitchng** [comment]
Thank you for bringing this to our attention. This issue was fixed in a release today (v0.1.6). You can get it on [npm](https://www.npmjs.com/package/adonisjs-queue)

**Comment by stitchng** [comment]
Since, this is all fixed. Closing out!

**Comment by sn0rcha** [comment]
Still getting this error with 0.1.7.

**Comment by 18601673727** [comment]
Even with 0.1.9, if I fire events inside a loop.

**Comment by mirkos93** [comment]
Even with 0.1.10 i've this error.
