### ISSUE TITLE
Update Yarn and Npm

### ISSUE THREAD

**Issue by harlancleiton** [stitchng/adonis-queue#8]
Please update package at [Npm](https://www.npmjs.com/package/adonisjs-queue) and [Yarn](https://yarnpkg.com/en/package/adonisjs-queue)

**Comment by stitchng** [comment]
Hello @harlancleiton . Thanks for your PR earlier. The package version(s) will be update between today and tomorrow

**Comment by stitchng** [comment]
NPM updated: v0.1.9

**Comment by harlancleiton** [comment]
Thank you
